# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('ADMIN_ID', models.IntegerField(db_column='ADMIN_ID', primary_key=True, serialize=False)),
                ('F_NAME', models.CharField(db_column='F_NAME', max_length=25)),
                ('L_NAME', models.CharField(db_column='L_NAME', max_length=25)),
                ('ADMIN_EMAIL_ID', models.TextField(db_column='ADMIN_EMAIL_ID', max_length=25)),
                ('ADMIN_PASS', models.TextField(db_column='ADMIN_PASS', max_length=7)),
                ('M_NAME', models.CharField(db_column='M_NAME', max_length=25)),
            ],
            options={
                'db_table': 'admin_user',
            },
        ),
        migrations.CreateModel(
            name='building_user',
            fields=[
                ('B_ADMIN_ID', models.IntegerField(db_column='B_ADMIN_ID', primary_key=True, serialize=False)),
                ('F_NAME', models.CharField(db_column='F_NAME', max_length=25)),
                ('L_NAME', models.CharField(db_column='L_NAME', max_length=25)),
                ('B_ADMIN_EMAIL_ID', models.TextField(db_column='B_ADMIN_EMAIL_ID', max_length=25)),
                ('B_ADMIN_PASS', models.TextField(db_column='B_ADMIN_PASS', max_length=25)),
                ('ADMIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite1.admin_user')),
            ],
            options={
                'db_table': 'building_user',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('DEPT_ID', models.IntegerField(db_column='DEPT_ID', primary_key=25, serialize=False)),
                ('DEPT_NAME', models.CharField(db_column='DEPT_NAME', max_length=25)),
                ('ADMIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite1.admin_user')),
                ('B_ADMIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite1.building_user')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENQUIRY', models.CharField(db_column='ENQUIRY', max_length=25)),
                ('COMPLAINT', models.CharField(db_column='COMPLAINT', max_length=25)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='normal_user',
            fields=[
                ('USER_ID', models.IntegerField(db_column='USER_ID', primary_key=25, serialize=False)),
                ('F_NAME', models.CharField(db_column='F_NAME', max_length=25)),
                ('L_NAME', models.CharField(db_column='L_NAME', max_length=25)),
                ('NORMAL_USER_EMAIL_ID', models.TextField(db_column='USER_EMAIL_ID', max_length=25)),
                ('NORMAL_USER_PASS', models.TextField(db_column='NORMAL_USER_PASS', max_length=25)),
                ('ADMIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite1.admin_user')),
                ('B_ADMIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite1.building_user')),
            ],
            options={
                'db_table': 'normal_user',
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('ROOM_ID', models.IntegerField(db_column='ROOM_ID', primary_key=25, serialize=False)),
                ('ROOM_TYPE', models.TextField(db_column='ROOM_TYPE', max_length=25)),
                ('B_ADMIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite1.building_user')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite1.normal_user')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='room_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOM_NAME', models.CharField(db_column='ROOM_NAME', max_length=25)),
                ('CAPACITY', models.CharField(db_column='CAPACITY', max_length=25)),
                ('ROOM_STATUS', models.CharField(db_column='ROOM_STATUS', max_length=25)),
                ('ROOM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite1.room')),
            ],
            options={
                'db_table': 'room_type',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite1.normal_user'),
        ),
    ]
