# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_user',
            name='NORMAL_USER_EMAIL_ID',
            field=models.TextField(db_column='NORMAL_USER_EMAIL_ID', max_length=25),
        ),
        migrations.AlterField(
            model_name='normal_user',
            name='USER_ID',
            field=models.IntegerField(db_column='USER_ID', primary_key=True, serialize=False),
        ),
    ]
